// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiposteOS.Infrastructure.Persistence;

#nullable disable

namespace RiposteOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RiposteDbContext))]
    [Migration("20260720091901_GeneralizeAiExecutionLogs")]
    partial class GeneralizeAiExecutionLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "identity");
                });

            modelBuilder.Entity("RiposteOS.Core.Ai.AiExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_ai_execution_logs_correlation_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_ai_execution_logs_provider_id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_ai_execution_logs_started_at");

                    b.ToTable("ai_execution_logs", "ai");
                });

            modelBuilder.Entity("RiposteOS.Core.Ai.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApiKeyEnvironmentVariableName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("HealthCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Unknown");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_providers_name");

                    b.ToTable("providers", "ai");
                });

            modelBuilder.Entity("RiposteOS.Core.Ai.AiTaskAssignment", b =>
                {
                    b.Property<string>("Task")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Task");

                    b.HasIndex("ProviderId");

                    b.ToTable("task_assignments", "ai");
                });

            modelBuilder.Entity("RiposteOS.Core.Ai.ConsultationDocumentClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Confidence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("StoredDocumentId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("evidencePassageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("evidence_passage_ids");

                    b.HasKey("Id");

                    b.HasIndex("StoredDocumentId");

                    b.HasIndex("ConsultationId", "StoredDocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_document_classifications_consultation_document");

                    b.ToTable("consultation_document_classifications", "ai");
                });

            modelBuilder.Entity("RiposteOS.Core.Consultations.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Buyer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NoticeUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResponseDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .IsUnique()
                        .HasDatabaseName("ux_consultations_opportunity_id")
                        .HasFilter("\"OpportunityId\" IS NOT NULL");

                    b.HasIndex("ResponseDeadline", "Id")
                        .HasDatabaseName("ix_consultations_response_deadline_id");

                    b.ToTable("consultations", "consultations");
                });

            modelBuilder.Entity("RiposteOS.Core.Consultations.ConsultationDocument", b =>
                {
                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoredDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KindOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Manual");

                    b.HasKey("ConsultationId", "StoredDocumentId");

                    b.HasIndex("StoredDocumentId")
                        .HasDatabaseName("ix_consultation_documents_stored_document_id");

                    b.HasIndex("ConsultationId", "AddedAt", "StoredDocumentId")
                        .HasDatabaseName("ix_consultation_documents_consultation_added_at_id");

                    b.ToTable("consultation_documents", "consultations");
                });

            modelBuilder.Entity("RiposteOS.Core.Documents.DocumentPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DocumentProcessingRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SectionTitle")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SourceLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentProcessingRunId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_document_passages_run_ordinal");

                    b.ToTable("document_passages", "documents");
                });

            modelBuilder.Entity("RiposteOS.Core.Documents.DocumentProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int>("PassageCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("StoredDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoredDocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_document_processing_runs_stored_document_id");

                    b.ToTable("document_processing_runs", "documents");
                });

            modelBuilder.Entity("RiposteOS.Core.Documents.StoredDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_stored_documents_storage_key");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_stored_documents_created_at_id");

                    b.ToTable("stored_documents", "documents");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.ImportIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_import_issues_run_id");

                    b.ToTable("import_issues", "sourcing");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Created")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CurrentPublicationDate")
                        .HasColumnType("date");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Fetched")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Unchanged")
                        .HasColumnType("integer");

                    b.Property<int>("Updated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QueuedAt")
                        .HasDatabaseName("ix_import_runs_queued_at");

                    b.HasIndex("Source")
                        .IsUnique()
                        .HasDatabaseName("ix_import_runs_active_source")
                        .HasFilter("\"Status\" IN ('Queued', 'Running')");

                    b.ToTable("import_runs", "sourcing");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Buyer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContractNature")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("EformsNoticeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("ExecutionDuration")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("NoticeUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ProcedureType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ResponseDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<string[]>("_countryCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("CountryCodes");

                    b.PrimitiveCollection<string[]>("_cpvCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("CpvCodes");

                    b.PrimitiveCollection<string[]>("_departmentCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("DepartmentCodes");

                    b.PrimitiveCollection<string[]>("_descriptorCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("DescriptorCodes");

                    b.PrimitiveCollection<string[]>("_descriptorLabels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("DescriptorLabels");

                    b.PrimitiveCollection<string[]>("_matchReasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("MatchReasons");

                    b.HasKey("Id");

                    b.HasIndex("EformsNoticeId")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunities_eforms_notice_id")
                        .HasFilter("\"EformsNoticeId\" IS NOT NULL");

                    b.HasIndex("MatchScore")
                        .HasDatabaseName("ix_opportunities_match_score");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_opportunities_status");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunities_source_source_id");

                    b.ToTable("opportunities", "sourcing");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.OpportunityPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoticeUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_opportunity_publications_opportunity_id");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunity_publications_source_source_id");

                    b.ToTable("opportunity_publications", "sourcing");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.OpportunityRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId", "CreatedAt")
                        .HasDatabaseName("ix_opportunity_revisions_opportunity_created_at");

                    b.ToTable("opportunity_revisions", "sourcing");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.SourcingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("BoampCron")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("0 * * * *");

                    b.Property<int>("CpvExclusionPenalty")
                        .HasColumnType("integer");

                    b.Property<int>("CpvWatchBoost")
                        .HasColumnType("integer");

                    b.Property<int>("CpvWhitelistBoost")
                        .HasColumnType("integer");

                    b.Property<int>("HighRelevanceThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("NegativeSignalPenalty")
                        .HasColumnType("integer");

                    b.Property<int>("PageSize")
                        .HasColumnType("integer");

                    b.Property<string>("PlaceCron")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("0 6,18 * * *");

                    b.Property<int>("PositiveSignalWeight")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredDepartmentBoost")
                        .HasColumnType("integer");

                    b.Property<string>("TedCron")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("0 * * * *");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UrgentDeadlineDays")
                        .HasColumnType("integer");

                    b.Property<int>("UrgentDeadlinePenalty")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("_allowedCountryCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("AllowedCountryCodes");

                    b.PrimitiveCollection<string[]>("_cpvExcludedPrefixes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("CpvExcludedPrefixes");

                    b.PrimitiveCollection<string[]>("_cpvWatchPrefixes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("CpvWatchPrefixes");

                    b.PrimitiveCollection<string[]>("_cpvWhitelistPrefixes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("CpvWhitelistPrefixes");

                    b.PrimitiveCollection<string[]>("_excludedKeywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ExcludedKeywords");

                    b.PrimitiveCollection<string[]>("_keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Keywords");

                    b.PrimitiveCollection<string[]>("_negativeSignals")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("NegativeSignals");

                    b.PrimitiveCollection<string[]>("_positiveSignals")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("PositiveSignals");

                    b.PrimitiveCollection<string[]>("_preferredDepartmentCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("PreferredDepartmentCodes");

                    b.HasKey("Id");

                    b.ToTable("sourcing_settings", "sourcing");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.SourcingSyncState", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("LastSuccessfulPublicationDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Source");

                    b.ToTable("sourcing_sync_states", "sourcing");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiposteOS.Core.Ai.AiTaskAssignment", b =>
                {
                    b.HasOne("RiposteOS.Core.Ai.AiProvider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RiposteOS.Core.Ai.ConsultationDocumentClassification", b =>
                {
                    b.HasOne("RiposteOS.Core.Consultations.Consultation", null)
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiposteOS.Core.Documents.StoredDocument", null)
                        .WithMany()
                        .HasForeignKey("StoredDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RiposteOS.Core.Consultations.Consultation", b =>
                {
                    b.HasOne("RiposteOS.Core.Sourcing.Opportunity", null)
                        .WithOne()
                        .HasForeignKey("RiposteOS.Core.Consultations.Consultation", "OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RiposteOS.Core.Consultations.ConsultationDocument", b =>
                {
                    b.HasOne("RiposteOS.Core.Consultations.Consultation", null)
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiposteOS.Core.Documents.StoredDocument", null)
                        .WithMany()
                        .HasForeignKey("StoredDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RiposteOS.Core.Documents.DocumentPassage", b =>
                {
                    b.HasOne("RiposteOS.Core.Documents.DocumentProcessingRun", "DocumentProcessingRun")
                        .WithMany()
                        .HasForeignKey("DocumentProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentProcessingRun");
                });

            modelBuilder.Entity("RiposteOS.Core.Documents.DocumentProcessingRun", b =>
                {
                    b.HasOne("RiposteOS.Core.Documents.StoredDocument", "StoredDocument")
                        .WithMany()
                        .HasForeignKey("StoredDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoredDocument");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.ImportIssue", b =>
                {
                    b.HasOne("RiposteOS.Core.Sourcing.ImportRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.OpportunityPublication", b =>
                {
                    b.HasOne("RiposteOS.Core.Sourcing.Opportunity", "Opportunity")
                        .WithMany("Publications")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.OpportunityRevision", b =>
                {
                    b.HasOne("RiposteOS.Core.Sourcing.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("RiposteOS.Core.Sourcing.Opportunity", b =>
                {
                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
