/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResponsesRouteImport } from './routes/_authenticated/responses'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedConsultationsRouteImport } from './routes/_authenticated/consultations'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedConsultationsIndexRouteImport } from './routes/_authenticated/consultations.index'
import { Route as AuthenticatedSettingsSourcingRouteImport } from './routes/_authenticated/settings.sourcing'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings.ai'
import { Route as AuthenticatedConsultationsConsultationIdRouteImport } from './routes/_authenticated/consultations.$consultationId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponsesRoute = AuthenticatedResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultationsRoute =
  AuthenticatedConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedConsultationsIndexRoute =
  AuthenticatedConsultationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsultationsRoute,
  } as any)
const AuthenticatedSettingsSourcingRoute =
  AuthenticatedSettingsSourcingRouteImport.update({
    id: '/sourcing',
    path: '/sourcing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRoute,
} as any)
const AuthenticatedConsultationsConsultationIdRoute =
  AuthenticatedConsultationsConsultationIdRouteImport.update({
    id: '/$consultationId',
    path: '/$consultationId',
    getParentRoute: () => AuthenticatedConsultationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/consultations': typeof AuthenticatedConsultationsRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/responses': typeof AuthenticatedResponsesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/consultations/$consultationId': typeof AuthenticatedConsultationsConsultationIdRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/sourcing': typeof AuthenticatedSettingsSourcingRoute
  '/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/responses': typeof AuthenticatedResponsesRoute
  '/': typeof AuthenticatedIndexRoute
  '/consultations/$consultationId': typeof AuthenticatedConsultationsConsultationIdRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/sourcing': typeof AuthenticatedSettingsSourcingRoute
  '/consultations': typeof AuthenticatedConsultationsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/consultations': typeof AuthenticatedConsultationsRouteWithChildren
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/responses': typeof AuthenticatedResponsesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/consultations/$consultationId': typeof AuthenticatedConsultationsConsultationIdRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/sourcing': typeof AuthenticatedSettingsSourcingRoute
  '/_authenticated/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/consultations'
    | '/knowledge'
    | '/opportunities'
    | '/responses'
    | '/settings'
    | '/consultations/$consultationId'
    | '/settings/ai'
    | '/settings/sourcing'
    | '/consultations/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/knowledge'
    | '/opportunities'
    | '/responses'
    | '/'
    | '/consultations/$consultationId'
    | '/settings/ai'
    | '/settings/sourcing'
    | '/consultations'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/consultations'
    | '/_authenticated/knowledge'
    | '/_authenticated/opportunities'
    | '/_authenticated/responses'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/consultations/$consultationId'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/sourcing'
    | '/_authenticated/consultations/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responses': {
      id: '/_authenticated/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof AuthenticatedResponsesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations': {
      id: '/_authenticated/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AuthenticatedConsultationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/consultations/': {
      id: '/_authenticated/consultations/'
      path: '/'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AuthenticatedConsultationsIndexRouteImport
      parentRoute: typeof AuthenticatedConsultationsRoute
    }
    '/_authenticated/settings/sourcing': {
      id: '/_authenticated/settings/sourcing'
      path: '/sourcing'
      fullPath: '/settings/sourcing'
      preLoaderRoute: typeof AuthenticatedSettingsSourcingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/consultations/$consultationId': {
      id: '/_authenticated/consultations/$consultationId'
      path: '/$consultationId'
      fullPath: '/consultations/$consultationId'
      preLoaderRoute: typeof AuthenticatedConsultationsConsultationIdRouteImport
      parentRoute: typeof AuthenticatedConsultationsRoute
    }
  }
}

interface AuthenticatedConsultationsRouteChildren {
  AuthenticatedConsultationsConsultationIdRoute: typeof AuthenticatedConsultationsConsultationIdRoute
  AuthenticatedConsultationsIndexRoute: typeof AuthenticatedConsultationsIndexRoute
}

const AuthenticatedConsultationsRouteChildren: AuthenticatedConsultationsRouteChildren =
  {
    AuthenticatedConsultationsConsultationIdRoute:
      AuthenticatedConsultationsConsultationIdRoute,
    AuthenticatedConsultationsIndexRoute: AuthenticatedConsultationsIndexRoute,
  }

const AuthenticatedConsultationsRouteWithChildren =
  AuthenticatedConsultationsRoute._addFileChildren(
    AuthenticatedConsultationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsSourcingRoute: typeof AuthenticatedSettingsSourcingRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsSourcingRoute: AuthenticatedSettingsSourcingRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsultationsRoute: typeof AuthenticatedConsultationsRouteWithChildren
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedResponsesRoute: typeof AuthenticatedResponsesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsultationsRoute: AuthenticatedConsultationsRouteWithChildren,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedResponsesRoute: AuthenticatedResponsesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
